name: main
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "15 0 * * 0"
jobs:
  main:
    runs-on: ubuntu-latest
    container: codecache/terraform:latest
    steps:
      - name: key
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: clone
        run: git clone git@github.com:codecache/example-private.git
      - name: validate
        run: cat example-private/README.md
