name: ubuntu
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "15 0 * * 0"
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: clone
        run: git clone git@github.com:codecache/example-private.git
      - name: validate
        run: cat example-private/README.md
